name: Build Gradle project

on:
  push:
    branches:
        - trunk
  pull_request:
    branches:
        - trunk

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        distribution: 'gradle'
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: List all files in the working directory before cd
      run: ls
    - name: Change directory to  project
      run: cd Application
    - name: List all files in the working directory after cd
      run: ls
    - name: Assign rights
      run: chmod +x ./gradlew 
    - name: Run build
      run: ./gradlew build
    - name: Run test
      run: ./gradlew  build -x test
    - run: echo "üçè This job's status is ${{ job.status }}."